do_overwrite: false  
seed: 42
save_dir: "./experiments/finetune/${now:%Y-%m-%d_%H-%M-%S}"
dataset_path: null
config:
  _target_: EventStream.transformer.config.StructuredTransformerConfig
  problem_type: "single_label_classification"
  num_labels: 2
  measurements_per_generative_mode:
    SINGLE_LABEL_CLASSIFICATION: ['A1cGreaterThan7']
  do_use_learnable_sinusoidal_ATE: false
  do_split_embeddings: true
  categorical_embedding_dim: 32
  numerical_embedding_dim: 16
  static_embedding_mode: sum_all
  categorical_embedding_weight: 0.3
  numerical_embedding_weight: 0.5
  static_embedding_weight: 0.4
  dynamic_embedding_weight: 0.5
  do_normalize_by_measurement_index: false
  structured_event_processing_mode: conditionally_independent
  num_hidden_layers: 3
  seq_attention_types: ["global", "local"]
  seq_window_size: 168
  TTE_generation_layer_type: exponential
  head_dim: 8
  num_attention_heads: 4
  attention_dropout: 0.2
  input_dropout: 0.2
  resid_dropout: 0.2
  intermediate_size: 256
  do_use_sinusoidal: true

optimization_config:
  init_lr: 0.0001
  end_lr_frac_of_init_lr: null
  end_lr: 0.00001
  max_epochs: 10
  batch_size: 8
  validation_batch_size: 8
  lr_frac_warmup_steps: 0.05
  lr_decay_power: 2
  weight_decay: 0.2
  patience: 2
  gradient_accumulation: 2
  num_dataloader_workers: 25
  lr_num_warmup_steps: 500
  max_training_steps: 1500

data_config:
  save_dir: "./data"
  dl_reps_dir: "data/DL_reps"
  dataset_path: null
  max_seq_len: 228
  subsequence_sampling_strategy: to_end
  min_seq_len: 4
  train_subset_size: 0.95
  train_subset_seed: 1
  task_df_name: null
  seq_padding_side: right
  do_include_subject_id: False
  do_include_start_time_min: False
  do_include_subsequence_indices: False
  
pretraining_metrics_config:
  do_skip_all_metrics: false
  do_validate_args: true
  include_metrics:
    TRAIN:
      LOSS_PARTS: true
      CLASSIFICATION:
        AUROC: true
        ACCURACY: true
    TUNING:
      CLASSIFICATION:
        AUROC: true
        ACCURACY: true

final_validation_metrics_config:
  n_auc_thresholds: 25
  do_skip_all_metrics: false
  do_validate_args: true
  include_metrics:
    TUNING:
      LOSS_PARTS: true
      CLASSIFICATION:
        AUROC: true
        ACCURACY: true  
    HELD_OUT:
      LOSS_PARTS: true
      CLASSIFICATION:
        AUROC: true
        ACCURACY: true

trainer_config:
  accelerator: "auto"
  devices: "auto"
  detect_anomaly: false
  log_every_n_steps: 10

experiment_dir: "./experiments"

wandb_logger_kwargs:
  name: "jvpoulos"
  project: "diabetes_finetune"
  team: null
  log_model: false

wandb_experiment_config_kwargs:
  entity: "jvpoulos"
  project: "diabetes_finetune"
  team: null
  log_model: false
  
do_final_validation_on_metrics: false
do_use_filesystem_sharing: false
